os: linux
dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y cpputest

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 CMAKE_CXX_COMPILER=/usr/bin/g++-7 CMAKE_C_COMPILER=/usr/bin/gcc-7 cmake .
  - cmake --build . -- -j2
  - ctest -j2 --output-on-failure
