name: CI Build Workflow

on:
  push:
    branches:
    - feature_branch

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir -p build
    - name: CMake Configuration
      run: cmake ..
      working-directory: ./build
    - name: CMake Build
      run: cmake --build .
      working-directory: ./build
