name: coverage
on: [push, pull_request]

jobs:
  codecheck:
    name: Code Coverage Stage
    runs-on: ubuntu-latest
    steps:
    - name: Install lcov
      run: sudo apt-get install -y lcov
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir build
    - name: Configuration
      run: cmake .. -DCMAKE_BUILD_TYPE=Coverage
      working-directory: ./build
    - name: Generate coverage
      run: cmake --build . --target coverage
      working-directory: ./build
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
