name: package
on: [push, pull_request]

jobs:
  package-source:
    name: Package Source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
    - name: Install ALSA/Jack - Ubuntu
      run: sudo apt-get update -y; sudo apt-get install -y libjack-dev libasound2-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install Jack - macOS
      run: brew install jack
      if: matrix.os == 'macos-latest'
    - name: Make Build Directory
      run: mkdir build
    - name: Make Install Directory
      run: mkdir install
      working-directory: ./build
    - name: Configuration on Ubuntu/MacOS
      run: cmake .. -DCMAKE_INSTALL_PREFIX=./install -DENABLE_UNIT_TESTS=OFF
      working-directory: ./build
      if: matrix.os != 'windows-latest'
    - name: Configuration on Windows
      run: cmake .. -DCMAKE_INSTALL_PREFIX=./install -DENABLE_UNIT_TESTS=OFF -DCMAKE_CONFIGURATION_TYPES=Release
      working-directory: ./build
      if: matrix.os == 'windows-latest'
    - name: Build Package Source
      run: cmake --build . --target package_source
      if: matrix.os == 'ubuntu-latest'
      working-directory: ./build
    - name: Build
      run: cmake --build .
      working-directory: ./build
    - name: Refresh Cache on Ubuntu/MacOS
      run: cmake .. -DCMAKE_INSTALL_PREFIX=./install -DENABLE_UNIT_TESTS=OFF
      working-directory: ./build
      if: matrix.os != 'windows-latest'
    - name: Refresh Cache on Windows
      run: cmake .. -DCMAKE_INSTALL_PREFIX=./install -DENABLE_UNIT_TESTS=OFF -DCMAKE_CONFIGURATION_TYPES=Release
      working-directory: ./build
      if: matrix.os == 'windows-latest'
    - name: Install
      run: cmake --build . --target install
      working-directory: ./build
    - name: Build Binary Packages
      run: cmake --build . --target package
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifacts
        path: ./build/brln-[0-9].*
