name: package
on: [push, pull_request]

jobs:
  package-source:
    name: Package Source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
    - name: Install ALSA/Jack - Ubuntu
      run: sudo apt-get update -y; sudo apt-get install -y libjack-dev libasound2-dev
    - name: Make Build Directory
      run: mkdir build
    - name: Configuration
      run: cmake .. -DENABLE_UNIT_TESTS=OFF
      working-directory: ./build
    - name: Build Package Source
      run: cmake --build . --target package_source
      working-directory: ./build
    - name: Upload Source-Zip
      uses: actions/upload-artifact@v2
      with:
        path: ./build/brln*Source.zip
