name: package
on: [push, pull_request]

jobs:
  package-source:
    name: Package Source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
    - name: Install ALSA/Jack - Ubuntu
      run: sudo apt-get update -y; sudo apt-get install -y libjack-dev libasound2-dev
      if: matrix.os == 'ubuntu-16.04'
    - name: Install Jack - macOS
      run: brew install jack
      if: matrix.os == 'macos-latest'
    - name: Make Build Directory
      run: mkdir build
    - name: Make Install Directory
      run: mkdir install
      working-directory: ./build
    - name: Configuration
      run: cmake .. -DENABLE_UNIT_TESTS=OFF
      working-directory: ./build
    - name: Build Package Source
      run: cmake --build . --target package_source
      if: matrix.os == 'ubuntu-16.04'
      working-directory: ./build
    - name: Build
      run: cmake --build . --config Release
      working-directory: ./build
    - name: Refresh Cache
      run: cmake ..
      working-directory: ./build
    - name: Build Binary Packages on MacOS/Windows
      run: cmake --build . --target package
      working-directory: ./build
      if: matrix.os != 'ubuntu-16.04'
    - name: Build AppImage on Ubuntu
      run: ./scripts/package-linux-appimage.sh .
      working-directory: ./build
      if: matrix.os == 'ubuntu-16.04'
    - name: Upload Artifact on MacOS/Windows
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifacts
        path: ./build/brln-[0-9].*
      if: matrix.os != 'ubuntu-16.04'
    - name: Upload Artifact on Ubuntu
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifacts
        path: ./build/dist/brln*.zip
      if: matrix.os == 'ubuntu-16.04'
