name: CI Workflow Playground

on:
  push:
    branches:
    - feature_branch

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir build
    - name: CMake Configuration for Win64
      run: cmake -DCMAKE_THREAD_LIBS_INIT=./_deps/libpd-src/libs/mingw64/libwinpthread-1.dll ..
      working-directory: ./build
    - name: CMake Build
      run: cmake --build .
      working-directory: ./build

  unittest:
    needs: [build]
    name: Unit Test Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Unit Test
      run: ctest
