name: Build and Unit Testing

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir build
    - name: CMake Configuration
      run: cmake ..
      working-directory: ./build
    - name: CMake Build
      run: cmake --build .
      working-directory: ./build

  unittest:
    needs: [build]
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Unit Test
      run: ctest
