name: CI Unit Test Workflow

on:
  push:
    branches:
    - feature_branch

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Git clone repository
      uses: actions/checkout@v2
    - name: Setup MinGW
      uses: numworks/setup-msys2@v1
    - name: Make Build Directory
      run: msys2do mkdir -p build
    - name: CMake Configuration
      run: msys2do cmake ..
      working-directory: ./build
    - name: CMake Build
      run: msys2do cmake --build .
      working-directory: ./build

  unittest:
    needs: [build]
    name: Unit Test Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Unit Test
      run: ctest
