name: CI Workflow Playground

on:
  push:
    branches:
    - feature_branch

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Make Build Directory
      run: mkdir build
    - name: CMake Configuration
      run: cmake ..
      working-directory: ./build
      if: !startsWith(matrix.os 'windows')
    - name: CMake Configuration
      run: cmake CMAKE_THREAD_LIBS_INIT=./_deps/libpd-src/libs/libwinpthread-1.dll ..
      working-directory: ./build
      if: startsWith(matrix.os 'windows')
    - name: CMake Build
      run: cmake --build .
      working-directory: ./build

  unittest:
    needs: [build]
    name: Unit Test Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Unit Test
      run: ctest
