name: CI Unit Test Workflow

on:
  push:
    branches:
    - feature_branch

jobs:
  unittest:
    needs: [build]
    name: Unit Test Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Unit Test
      run: ctest
